* bin/users: use wc -l, since pgrep -c doesn't work in some   distros (busybox, Arch), LP: #434047 * byobu.1: fix manpage, mem_used was listed twice, mail was in the wrong   place, LP: #434052

diff --git a/bin/users b/bin/users
--- a/bin/users
+++ b/bin/users
@@ -25,5 +25,7 @@ if [ "$1" = "--detail" ]; then
 	exit 0
 fi
 
-count=`pgrep -c -f "sshd:.*@"` || exit 0
+# Note: we'd like to use pgrep -c, however, this isn't available in
+# busybox and some distro's pgrep (and it doesn't exit non-zero).
+count=`pgrep -f "sshd:.*@" | wc -l` || exit 0
 printf "\005{=b wr}%d\005{-}\005{= wr}#\005{-} " $count
