* bin/cpu_count, bin/cpu_freq, bin/disk_available, bin/disk_used,     bin/ec2_cost, bin/ip_address, bin/load_average, bin/mem_available,     bin/mem_used, bin/network_down, bin/network_up, bin/reboot_required,     bin/temp_c, bin/temp_f, bin/updates_available, bin/wifi_quality,     byobu-config, byobu-export, byobu-status, byobu.1, debian/control,     doc/help.txt, profiles/common, rpm/byobu.spec: massive changeset, moving     all status scripts from *-* to *_*; this allows us to source the     ~/.byobu/status file, rather than grepping through it for configuration     information, yielding significant performance improvements, LP: #386546
Signed-off-by: Dustin Kirkland <kirkland@canonical.com>

diff --git a/byobu-status b/byobu-status
--- a/byobu-status
+++ b/byobu-status
@@ -47,6 +47,7 @@ migrate() {
 # If the old config dir exists, but the new one doesn't, provide a migration mechanism
 [ -d "$HOME/.$OLDPKG" -a ! -d "$HOME/.$PKG" ] && migrate
 
+# Allow for local status scripts
 if [ -d "$HOME/.$PKG/bin" ]; then
 	DIR="$HOME/.$PKG/bin"
 elif [ -d "/usr/lib/$PKG" ]; then
@@ -55,16 +56,25 @@ else
 	exit 1
 fi
 
+# Source status file
+if [ -r "$HOME/.$PKG/status" ]; then
+	if ! . "$HOME/.$PKG/status" ; then
+		# If sourcing fails, try replacing - with _
+		sed -i "s/-/_/g" "$HOME/.$PKG/status"
+	fi
+fi
+
 P="$1"
+eval x=\$$P
 
 case "$P" in
 	# default = on, user must override to turn off
-	cpu-count|cpu-freq|date|load-average|logo|mem-available|mem-used|menu|reboot-required|release|time|updates-available|uptime)
-		grep -qs -m1 "^$P=0$" "$HOME/.$PKG/status" && exit 0
+	cpu_count|cpu_freq|date|load_average|logo|mem_available|mem_used|menu|reboot_required|release|time|updates_available|uptime)
+		[ "$x" = "0" ] && exit 0
 	;;
 	# default = off, user must override to turn on
-	arch|battery|disk-available|disk-used|ec2-cost|hostname|ip-address|network-down|network-up|processes|users|temp-c|temp-f|whoami|wifi-quality)
-		grep -qs -m1 "^$P=1$" "$HOME/.$PKG/status" || exit 0
+	arch|battery|disk_available|disk_used|ec2_cost|hostname|ip_address|network_down|network_up|processes|users|temp_c|temp_f|whoami|wifi_quality)
+		[ "$x" = "1" ] || exit 0
 	;;
 	--detail)
 		VER=
