* byobu: make this script set -e, such that it will fail if byobu-janitor     exits non-zero   * byobu-janitor: check that ~/.byobu is writable; print an error message     and exit non-zero if not; handles odd situation where user launches     byobu from a sudo/root shell, and root owns their ~/.byobu dir, but then     they launch as non-root sometime later, LP: #394147
Signed-off-by: Dustin Kirkland <kirkland@canonical.com>

diff --git a/byobu-janitor b/byobu-janitor
--- a/byobu-janitor
+++ b/byobu-janitor
@@ -32,6 +32,13 @@ OLDPKG="screen-profiles"
 DEFAULT_PROFILE="light"
 PROFILE="$HOME/.$PKG/profile"
 
+# Affects: users who launched using sudo, such that their config dir
+# is not writable by them
+if [ -d "$HOME/.$PKG" ] && [ ! -w "$HOME/.$PKG" ]; then
+	echo "ERROR: [$HOME/.$PKG] is not writable by the current user" 1>&2
+	exit 1
+fi
+
 # Affects: Upgrades from screen-profiles
 # If the old config dir exists, but the new one doesn't, provide a migration mechanism.
 if [ -d "$HOME/.$OLDPKG" ] && [ ! -e "$HOME/.$PKG" ]; then
