* bin/ec2-cost, bin/hostname, bin/ip-address, bin/logo,     bin/mem-available, bin/network-down, bin/network-up,     bin/updates-available, debian/postrm, debian/preinst,     debian/release.sh, debian/rules, screen, screen-launcher-install,     screen-profiles, screen-profiles-export, screen-profiles-status,     select-screen-profile: abstract the package name (currently,     screen-profiles) to a variable
Signed-off-by: Dustin Kirkland <kirkland@canonical.com>

diff --git a/screen-profiles-export b/screen-profiles-export
--- a/screen-profiles-export
+++ b/screen-profiles-export
@@ -17,9 +17,9 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-PROG="screen-profiles"
-SHARE="/usr/share/$PROG"
-DIR=`mktemp -t -d screen-profiles.XXXXXXXX` || error "Could not create a temporary directory"
+PKG="screen-profiles"
+SHARE="/usr/share/$PKG"
+DIR=`mktemp -t -d $PKG.XXXXXXXX` || error "Could not create a temporary directory"
 # Grab list of available colors
 colors=`find $SHARE/profiles/ -type f | sed "s/^.*\///" | sed "s/^.*-//" | sort -u | egrep -v "common|plain|NONE"`
 
@@ -85,9 +85,9 @@ choose() {
 
 status_config() {
 	# Generate the status configuration
-	# Disable the menu, since screen-profiles configurator is not available
+	# Disable the menu, since configurator is not available
 	# Enable user@host in its place
-	for i in $(ls /usr/lib/screen-profiles/); do
+	for i in $(ls /usr/lib/$PKG/); do
 		case "$i" in
 			cpu-count|cpu-freq|date|hostname|load-average|logo|mem-available|mem-used|reboot-required|release|time|updates-available|whoami)
 				echo "$i=1"
@@ -105,12 +105,12 @@ hr() {
 
 header() {
 	hr
-	echo "# This GNU Screen profile was generated by the screen-profile-export"
-	echo "# program, which is part of the screen-profiles package, and contains a"
+	echo "# This GNU Screen profile was generated by the $PKG-export"
+	echo "# program, which is part of the $PKG package, and contains a"
 	echo "# subset of the functionality available from the full package."
 	echo "#"
 	echo "# For more information, source code, questions, and bugs, see:"
-	echo "#  * https://launchpad.net/screen-profiles"
+	echo "#  * https://launchpad.net/$PKG"
 	echo "#"
 	echo "#    Copyright (C) 2008 Canonical Ltd."
 	echo "#"
@@ -133,7 +133,7 @@ header() {
 sources() {
 	# insert the common profile, replace the status exe path
 	echo
-	cat $SHARE/profiles/common | sed "s:$PROG-status:\$HOME/.$PROG/$PROG-status:"
+	cat $SHARE/profiles/common | sed "s:$PKG-status:\$HOME/.$PKG/$PKG-status:"
 	hr
 	echo
 	cat $SHARE/keybindings/common
@@ -169,7 +169,7 @@ done
 if [ -z "$file" ]; then
 	# Generate a temp archive filename
 	while true; do
-		file=`mktemp -t screen-profiles.XXXXXX` || error "Could not generate random filename"
+		file=`mktemp -t $PKG.XXXXXX` || error "Could not generate random filename"
 		if [ ! -e "$file.tar.gz" ]; then
 			mv -i "$file" "$file.tar.gz"
 			file="$file.tar.gz"
@@ -217,12 +217,12 @@ done
 
 # Create workspace
 PROFILE="$DIR/.screenrc"
-STATUS="$DIR/.$PROG/status"
-mkdir -p "$DIR/.$PROG/bin"
+STATUS="$DIR/.$PKG/status"
+mkdir -p "$DIR/.$PKG/bin"
 
 # Copy status scripts
-cp -a /usr/lib/$PROG/* "$DIR/.$PROG/bin"
-cp -a /usr/bin/$PROG-status "$DIR/.$PROG"
+cp -a /usr/lib/$PKG/* "$DIR/.$PKG/bin"
+cp -a /usr/bin/$PKG-status "$DIR/.$PKG"
 
 # Generate the monolithic profile
 header > "$PROFILE"
@@ -233,7 +233,7 @@ status_config > "$STATUS"
 # Drop additional "source" calls
 sed -i "s:^source .*::" "$PROFILE"
 # Use .screenrc instead
-sed -i "s:.$PROG/profile\":\.screenrc\":" "$PROFILE"
+sed -i "s:.$PKG/profile\":\.screenrc\":" "$PROFILE"
 # Drop the F9->Menu key
 sed -i "s:^bindkey -k k9 screen -t help:#bindkey -k k9 screen -t help:" "$PROFILE"
 
