* screen-profile-helper allows to create new windows  * screen-profile-helper allows to select profiles

diff --git a/select-screen-profile b/select-screen-profile
--- a/select-screen-profile
+++ b/select-screen-profile
@@ -35,18 +35,28 @@ usage: select-screen-profiles [(-l|--list)][(-h|--help)][(-s|--set) PROFILE]
 EOT
 }
 
+# Initialize variables
 BASE_DIR="/usr/share/screen-profiles"
 PROFILE_DIR="$BASE_DIR/profiles"
+WINDOW_DIR="$BASE_DIR/windows"
 profile=""
 selected=-1
 
 # Ensure that ~/.screenrc-profile is a symbolic link
 if [ -e "$HOME/.screenrc-profile" ]; then
-	if [ ! -L "$HOME/.screenrc-profile" ]; then
-		echo `gettext 'Error:'` $HOME/.screenrc-profile `gettext ' file exists, but is not a symlink'`
-		exit 1
-	fi
+    if [ ! -L "$HOME/.screenrc-profile" ]; then
+        echo `gettext 'Error:'` $HOME/.screenrc-profile `gettext ' file exists, but is not a symlink'`
+        exit 1
+    fi
 fi
+# Ensure that ~/.screenrc-window is a symbolic link
+if [ -e "$HOME/.screenrc-window" ]; then
+    if [ ! -L "$HOME/.screenrc-window" ]; then
+        echo `gettext 'Error:'` $HOME/.screenrc-window `gettext ' file exists, but is not a symlink'`
+        exit 1
+    fi
+fi
+
 
 profiles=$(ls $PROFILE_DIR)            
 
@@ -81,12 +91,14 @@ prompt() {
 }
 
 listprofiles() {
+    # Display list of profiles, one per line
     for x in $profiles; do
         echo "$x"   
     done
 }
 
 setprofile() {
+    # Apply a profile by name ($profile) or index ($selected)
     i=0
     found=0
     for x in $profiles; do
@@ -95,20 +107,31 @@ setprofile() {
     		if [ ! -e "$HOME/.screenrc" ]; then
     			# If the user doesn't have a .screenrc, seed one
     			echo "source ~/.screenrc-profile" > "$HOME/.screenrc"
+                echo "source ~/.screenrc-window" >> "$HOME/.screenrc"
     		else
     			# If the user does have a .screenrc, see if it has the
-    			# source line
-    			if ! grep -qs "source $HOME/.screenrc-profile" "$HOME/.screenrc"; then
-    				# And if it's missing the source line, add it
-    				# to the top
-    				tmp=`mktemp "$HOME/.screenrc.XXXXXX"`
-    				echo "source $HOME/.screenrc-profile" > "$tmp"
-    				cat "$HOME/.screenrc" >> "$tmp"
-    				mv -f "$tmp" "$HOME/.screenrc"
-    			fi
+    			# sources lines
+                if ! grep -qs "source $HOME/.screenrc-profile" "$HOME/.screenrc"; then
+                    # And if it's missing the source line, add it
+                    # to the top
+                    tmp=`mktemp "$HOME/.screenrc.XXXXXX"`
+                    echo "source $HOME/.screenrc-profile" > "$tmp"
+                    cat "$HOME/.screenrc" >> "$tmp"
+                    mv -f "$tmp" "$HOME/.screenrc"
+                fi
+                if ! grep -qs "source $HOME/.screenrc-window" "$HOME/.screenrc"; then
+                    # And if it's missing the source line, add it
+                    # to the top
+                    tmp=`mktemp "$HOME/.screenrc.XXXXXX"`
+                    echo "source $HOME/.screenrc-window" > "$tmp"
+                    cat "$HOME/.screenrc" >> "$tmp"
+                    mv -f "$tmp" "$HOME/.screenrc"
+                fi
     		fi
     		rm -f "$HOME/.screenrc-profile"
+            rm -f "$HOME/.screenrc-window"
     		ln -s "$PROFILE_DIR/$x" "$HOME/.screenrc-profile"
+            ln -s "$WINDOW_DIR/default" "$HOME/.screenrc-window"
     		found=1
     	fi
     done
