* usr/bin/byobu-status, usr/lib/byobu/apport, usr/lib/byobu/arch,   usr/lib/byobu/battery, usr/lib/byobu/.constants,   usr/lib/byobu/cpu_count, usr/lib/byobu/cpu_freq,   usr/lib/byobu/cpu_temp, usr/lib/byobu/custom, usr/lib/byobu/date,   usr/lib/byobu/disk, usr/lib/byobu/disk_io, usr/lib/byobu/ec2_cost,   usr/lib/byobu/fan_speed, usr/lib/byobu/hostname,   usr/lib/byobu/ip_address, usr/lib/byobu/load_average,   usr/lib/byobu/logo, usr/lib/byobu/mail, usr/lib/byobu/mem_available,   usr/lib/byobu/mem_used, usr/lib/byobu/menu, usr/lib/byobu/network,   usr/lib/byobu/notify_osd, usr/lib/byobu/processes,   usr/lib/byobu/raid, usr/lib/byobu/rcs_cost,   usr/lib/byobu/reboot_required, usr/lib/byobu/release,   usr/lib/byobu/services, usr/lib/byobu/.shutil, usr/lib/byobu/swap,   usr/lib/byobu/time, usr/lib/byobu/time_utc, usr/lib/byobu/trash,   usr/lib/byobu/updates_available, usr/lib/byobu/uptime,   usr/lib/byobu/users, usr/lib/byobu/whoami,   usr/lib/byobu/wifi_quality:   - rework status scripts into sourcable functions   - update copyright info, update email address, standardize headers

diff --git a/usr/lib/byobu/users b/usr/lib/byobu/users
--- a/usr/lib/byobu/users
+++ b/usr/lib/byobu/users
@@ -1,39 +1,38 @@
 #!/bin/sh -e
 #
-#  users: print the number of remote users on the machine
-#  Copyright (C) 2009 Raphaël Pinson.
-#  Copyright (C) 2009 Canonical Ltd.
+#    users: print the number of remote users on the machine
 #
-#  Authors: Raphaël Pinson <raphink@ubuntu.com>
-#           Dustin Kirkland <kirkland@canonical.com>
+#    Copyright (C) 2009 Raphaël Pinson.
+#    Copyright (C) 2009 Canonical Ltd.
+#    Copyright (C) 2011 Dustin Kirkland
 #
-#  This program is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation, version 3 of the License.
+#    Authors: Raphaël Pinson <raphink@ubuntu.com>
+#             Dustin Kirkland <kirkland@ubuntu.com>
 #
-#  This program is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, version 3 of the License.
 #
-#  You should have received a copy of the GNU General Public License
-#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
 #
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-PKG="byobu"
-color 2>/dev/null || color() { true; }
-
-if [ "$1" = "--detail" ]; then
+__users_detail() {
 	ps -ef | grep "sshd;.*@" | grep -v grep
-	exit 0
-fi
+}
 
-# Note: we'd like to use pgrep -c, however, this isn't available in
-# busybox and some distro's pgrep (and it doesn't exit non-zero).
-count=`pgrep -f "sshd:.*@" | wc -l` || exit 0
-
-if [ $count -gt 0 ]; then
-	color b w r; printf "%d" "$count"; color -; color w r; printf "#"; color --
-fi
+__users() {
+	local count
+	# Note: we'd like to use pgrep -c, however, this isn't available in
+	# busybox and some distro's pgrep (and it doesn't exit non-zero).
+	count=`pgrep -f "sshd:.*@" | wc -l` || return
+	if [ $count -gt 0 ]; then
+		color b w r; printf "%d" "$count"; color -; color w r; printf "#"; color --
+	fi
+}
 
 # vi: syntax=sh ts=4 noexpandtab
