usr/lib/byobu/rcs_cost, usr/lib/byobu/time_binary,   usr/lib/byobu/include/common, usr/lib/byobu/include/mondrian,   usr/lib/byobu/include/shutil:

diff --git a/usr/lib/byobu/include/common b/usr/lib/byobu/include/common
--- a/usr/lib/byobu/include/common
+++ b/usr/lib/byobu/include/common
@@ -44,7 +44,7 @@ if [ -z "${BYOBU_INCLUDED_LIBS}" ]; then
 				unset i
 			fi
 			if ! command -v "$BYOBU_BACKEND" >/dev/null; then
-				echo "ERROR: $PKG won't work without tmux or screen installed" 1>&2
+				printf "%s\n" "ERROR: $PKG won't work without tmux or screen installed" 1>&2
 			fi
 		fi
   	fi
