* usr/bin/byobu, usr/bin/byobu-launch, usr/bin/byobu-launcher,   usr/share/man/man1/byobu.1: LP: #835152   - fix a suite of support issues around launching byobu under sudo,     where files/dirs would be created under the $SUDO_USER's $HOME,     but would be owned by root

diff --git a/usr/bin/byobu b/usr/bin/byobu
--- a/usr/bin/byobu
+++ b/usr/bin/byobu
@@ -18,8 +18,19 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 VERSION=4.32
-
 PKG="byobu"
+
+# All sorts of things go wrong if you don't own your $HOME dir.
+# This happens under sudo, if you don't use the -H option; Byobu will
+# create a bunch of files in your $HOME which will be owned by root.
+if [ ! -O "$HOME" ]; then
+	echo "Cannot run $PKG because [$USER] does not own [$HOME]" 1>&2
+	if [ -n "$SUDO_USER" ]; then
+		echo "To run $PKG under sudo, you MUST use 'sudo -H'" 1>&2
+	fi
+	exit 1
+fi
+
 [ -z "${BYOBU_PREFIX}" ] && export BYOBU_PREFIX="/usr" || export BYOBU_PREFIX
 . "${BYOBU_PREFIX}/lib/${PKG}/.common"
 
