* configure.ac, etc/profile.d/Z97-byobu.sh => etc/profile.d/Z97-   byobu.sh.in, usr/bin/byobu-config => usr/bin/byobu-config.in,   usr/bin/byobu-ctrl-a => usr/bin/byobu-ctrl-a.in, usr/bin/byobu-   disable-prompt => usr/bin/byobu-disable-prompt.in, usr/bin/byobu-   disable => usr/bin/byobu-disable.in, usr/bin/byobu-enable-prompt =>   usr/bin/byobu-enable-prompt.in, usr/bin/byobu-enable =>   usr/bin/byobu-enable.in, usr/bin/byobu-export => usr/bin/byobu-   export.in, usr/bin/byobu-janitor => usr/bin/byobu-janitor.in,   usr/bin/byobu-launcher-install => usr/bin/byobu-launcher-install.in,   usr/bin/byobu-launcher-uninstall => usr/bin/byobu-launcher-   uninstall.in, usr/bin/byobu-launcher => usr/bin/byobu-launcher.in,   usr/bin/byobu-launch => usr/bin/byobu-launch.in, usr/bin/byobu-   layout => usr/bin/byobu-layout.in, usr/bin/byobu-prompt =>   usr/bin/byobu-prompt.in, usr/bin/byobu-quiet => usr/bin/byobu-   quiet.in, usr/bin/byobu-reconnect-sockets => usr/bin/byobu-   reconnect-sockets.in, usr/bin/byobu-select-backend => usr/bin/byobu-   select-backend.in, usr/bin/byobu-select-profile => usr/bin/byobu-   select-profile.in, usr/bin/byobu-select-session => usr/bin/byobu-   select-session.in, usr/bin/byobu-shell => usr/bin/byobu-shell.in,   usr/bin/byobu-silent => usr/bin/byobu-silent.in, usr/bin/byobu-   status-detail => usr/bin/byobu-status-detail.in, usr/bin/byobu-   status => usr/bin/byobu-status.in, usr/bin/byobu-ugraph =>   usr/bin/byobu-ugraph.in, usr/bin/byobu-ulevel => usr/bin/byobu-   ulevel.in, usr/bin/byobu => usr/bin/byobu.in,   usr/lib/byobu/include/config.py =>   usr/lib/byobu/include/config.py.in, usr/lib/byobu/include/dirs =>   usr/lib/byobu/include/dirs.in, usr/lib/byobu/include/toggle-utf8 =>   usr/lib/byobu/include/toggle-utf8.in, usr/share/byobu/tests/byobu-   time-notifications => usr/share/byobu/tests/byobu-time-   notifications.in:   - use @prefix@ rather than hardcoding /usr, makes code     more portable and easier to build with ./config --prefix

diff --git a/usr/bin/byobu-quiet.in b/usr/bin/byobu-quiet.in
--- a/usr/bin/byobu-quiet.in
+++ b/usr/bin/byobu-quiet.in
@@ -1,7 +1,7 @@
-#!/bin/sh -e
+#!/bin/sh
 #
-#    byobu-enable: enable and launch byobu
-#    Copyright (C) 2010 Canonical Ltd.
+#    byobu-quiet - disable the hardstatus and all indicators
+#    Copyright (C) 2011 Canonical Ltd.
 #
 #    Authors: Dustin Kirkland <kirkland@byobu.co>
 #
@@ -19,20 +19,21 @@
 
 PKG="byobu"
 [ -r "$HOME/.byoburc" ] && . "$HOME/.byoburc"
-[ -z "${BYOBU_PREFIX}" ] && export BYOBU_PREFIX="/usr" || export BYOBU_PREFIX
+[ -z "${BYOBU_PREFIX}" ] && export BYOBU_PREFIX="@prefix@" || export BYOBU_PREFIX
 . "${BYOBU_PREFIX}/lib/${PKG}/include/common"
 
-byobu-launcher-install
+FLAG="$BYOBU_CONFIG_DIR/status.disable"
 
-echo
-echo "The Byobu window manager will be launched automatically at each text login."
-echo
-echo "To disable this behavior later, just run:"
-echo "  byobu-disable"
-echo
-printf "Press <enter> to continue..."
-$(head -n1)
-
-exec byobu
+# Clean up environment
+$BYOBU_SED -i "/hardstatus/d" "$BYOBU_CONFIG_DIR/keybindings" || true
+if [ "$1" = "--undo" ]; then
+	rm -f "$FLAG"
+else
+	touch "$FLAG"
+	# BUG: Need to make this dynamic and following
+	status="$USER@$(hostname)"
+	echo "hardstatus lastline '$status'" >> "$BYOBU_CONFIG_DIR/keybindings"
+fi
+$BYOBU_BACKEND -X at 0 source "$BYOBU_CONFIG_DIR/profile"
 
 # vi: syntax=sh ts=4 noexpandtab
diff --git a/usr/bin/byobu-silent.in b/usr/bin/byobu-silent.in
--- a/usr/bin/byobu-silent.in
+++ b/usr/bin/byobu-silent.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-#    byobu-shell: display the MOTD and launch the default shell
-#    Copyright (C) 2008 Canonical Ltd.
+#    byobu-silence - disable the hardstatus, all indicators, and the window list
+#    Copyright (C) 2011 Canonical Ltd.
 #
 #    Authors: Dustin Kirkland <kirkland@byobu.co>
 #
@@ -19,25 +19,19 @@
 
 PKG="byobu"
 [ -r "$HOME/.byoburc" ] && . "$HOME/.byoburc"
-[ -z "${BYOBU_PREFIX}" ] && export BYOBU_PREFIX="/usr" || export BYOBU_PREFIX
+[ -z "${BYOBU_PREFIX}" ] && export BYOBU_PREFIX="@prefix@" || export BYOBU_PREFIX
 . "${BYOBU_PREFIX}/lib/${PKG}/include/common"
 
-FLAG="$BYOBU_CONFIG_DIR/.welcome-displayed"
+FLAG="$BYOBU_CONFIG_DIR/status.disable"
 
-[ -r /etc/motd ] && cat /etc/motd
-
-if [ ! -e "$FLAG" ]; then
-	echo
-	echo "Welcome to the light, powerful, text window manager, Byobu."
-	echo "You can toggle the launch of Byobu at login with:"
-	echo "  'byobu-disable' and 'byobu-enable'"
-	echo
-	echo "For tips, tricks, and more information, see:"
-	echo " * http://bit.ly/byobu-help"
-	echo
+# Clean up environment
+$BYOBU_SED -i "/caption/d" "$BYOBU_CONFIG_DIR/keybindings" || true
+if [ "$1" = "--undo" ]; then
+	rm -f "$FLAG"
+else
 	touch "$FLAG"
+	echo "caption splitonly ''" >> "$BYOBU_CONFIG_DIR/keybindings"
 fi
-
-[ -n "$SHELL" -a -x "$SHELL" ] && exec "$SHELL" || exec /bin/sh
+exec byobu-quiet "$@"
 
 # vi: syntax=sh ts=4 noexpandtab
