* usr/bin/byobu-reconnect-sockets, usr/lib/byobu/date,   usr/share/byobu/keybindings/f-keys,   usr/share/byobu/keybindings/screen-escape-keys:   - add a ctrl-f5 keybinding for reconnecting sockets

diff --git a/usr/bin/byobu-reconnect-sockets b/usr/bin/byobu-reconnect-sockets
--- a/usr/bin/byobu-reconnect-sockets
+++ b/usr/bin/byobu-reconnect-sockets
@@ -21,17 +21,19 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+PKG="byobu"
 
 case "$-" in
 	*i*)
 		# no-op
 	;;
 	*)
-		echo
-		echo "ERROR: You must source this file, rather than execute it."
-		echo "  . $0"
-		echo
-		#exit 1
+		# screen -X -S "$PKG" at "$USER*" stuff ". $0"; then
+		echo 2>&1
+		echo "ERROR: You must source this file, rather than execute it." 2>&1
+		echo "  . $0" 2>&1
+		echo 2>&1
+		exit 1
 	;;
 esac
 
