* usr/bin/vigpg:   - specify stdin for input file

diff --git a/usr/bin/vigpg b/usr/bin/vigpg
--- a/usr/bin/vigpg
+++ b/usr/bin/vigpg
@@ -48,7 +48,7 @@ fi
 
 # Try to decrypt the target file
 if [ -e "$encrypted_file" ]; then
-	(cat "$encrypted_file" | gpg -d > "$cleartext_file") 		|| error "Unable to decrypt target"
+	(cat "$encrypted_file" | gpg -d - > "$cleartext_file") 		|| error "Unable to decrypt target"
 fi
 
 # Grab a checksum of the cleartext data before modification
